### ISSUE TITLE
Weird error display

### ISSUE THREAD

**Issue by Simn** [nadako/vshaxe#1]
Haxe outputs this:

```
> src/hxparse/RuleBuilder.hx:19: lines 19-69 : Array<haxe.macro.Field> should be haxe.macro.Expr
```

Which is displayed like this on hovering:

```
should be haxe.macro.Expr
src/hxparse/RuleBuilder.hx:19: lines 19-69 : Array
```

**Comment by nadako** [comment]
Yeah I also get this sometimes. I still wonder if it's haxe issue with error prefixing or `HaxeServer.hx` one with it's parsing. WIll look into it.

**Comment by nadako** [comment]
After d3d7284a743553584e3e2f664af4b8462558423b this should now display a proper error.
